### ISSUE TITLE
Gets confused with pydocstyle (Dxxx) violations

### ISSUE THREAD

**Issue by plinss** [plinss/flake8-noqa#1]
If a line has a Dxxx violation and you add a `# noqa: Dxxx` flake-noqa starts complaining that Dxxx isn't matched on that line.

This is due to the fact that pydocstyle parses the `# noqa` comment itself and never sends the violation report to flake8, so flake8-noqa stops seeing it.

Issue filed on pydocstyle to add a `--disable-noqa` equivalent, and will be followed by an issue on flake8-docstyle to invoke the option. Note the same issue also affects `flake8 --disable-noqa`, it still won't show violations reported by pydocstyle and blocked by `# noqa` comments regardless if this plugin is used or not.

Should the issues on pydocstyle and flake8-docstyle be rejected, will look for some kind of less-than-ideal workaround.

**Comment by jonyscathe** [comment]
Looks to be a similar issue with flake8-print violations, at least with T001.

With `print('test')  # noqa: T001` we get 'NQA102 (flake8-noqa) "# noqa: T001" has no matching violations'
With just `print('test')` we get `T001 print found.`

With `print('test')  # noqa` it works ok, but that is a pretty average solution.

**Comment by scop** [comment]
Looks like the pydocstyle issue was taken care of, I wonder what the status for the rest of TODOs to get flake8-docstrings to cooperate is?

**Comment by plinss** [comment]
Just waiting for this to get merged: https://gitlab.com/pycqa/flake8-docstrings/-/merge_requests/29

**Comment by plinss** [comment]
Fixed in flake8-docstrings v1.6.0

**Comment by provinzkraut** [comment]
Are there any recommendations on how to handle this when not using a flake8 integration for `pydocstyle`?
Unfortunately `flake8-docstyle` isn't suitable for use due to its limited configuration options, so we have to use `pydocstyle` directly.
