### ISSUE TITLE
Support flake8==5

### ISSUE THREAD

**Issue by jonyscathe** [plinss/flake8-noqa#16]
Currently setup.py is limiting flake8 < 5
I would like to move to flakeu8==5.0.2.
Does anything (other than setup.py) need to change for this?

**Comment by plinss** [comment]
I'm generally conservative allowing new releases of flake8 because this plugin does do a small amount of monkey patching, so it's always possible that a new release a flake8 will break it. But the unit tests look good on flake8 5.0.3.

Thanks for the ping, I wasn't aware 5.0 had shipped.

**Comment by jonyscathe** [comment]
Thanks for the quick fix!
