### ISSUE TITLE
LICENSE vs. COPYING.LESSER inconsistency

### ISSUE THREAD

**Issue by mtelka** [plinss/flake8-noqa#23]
The 1.3.0 sdist at PyPI shows this as the License-File:
```
$ grep License-File PKG-INFO 
License-File: LICENSE
$
```
While at the same time it claims the project license is LGPL v3:
```
$ grep License: PKG-INFO 
License: GNU Lesser General Public License v3
$
```
But the `LICENSE` file contains GPL v3, not LGPL v3:
```
$ head -n2 LICENSE 
                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007
$
```
The LGPL v3 is actually in the `COPYING.LESSER` file:
```
$ head -n2 COPYING.LESSER 
                   GNU LESSER GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007
$
```

**Comment by mtelka** [comment]
Please note this is regression from 1.2.9 where both `LICENSE` and `COPYING.LESSER` files were referenced as License-File in the `PKG-INFO` file.

**Comment by mtelka** [comment]
This is fixed in flake8-noqa 1.3.2.  Thanks.

**Comment by plinss** [comment]
FWIW, I didn't change anything. I'm guessing the actual regression (and fix) was in the build tooling that creates the package (I did switch to pyproject.toml at v1.3.0).

My understanding of the LGPL is that it's an addendum to the GPL as opposed to a stand-alone license, so both files need to exist to apply the LGPL properly.

**Comment by mtelka** [comment]
Yes, you are right.  The other option is to include one single file with combined LGPL+GPL. See https://www.gnu.org/licenses/lgpl-3.0.html and https://www.gnu.org/licenses/lgpl+gpl-3.0.txt.
