### ISSUE TITLE
Allow ignoring T000 (TODO marker)

### ISSUE THREAD

**Issue by PeterJCLaw** [plinss/flake8-noqa#29]
Given the following code:
``` python
# TODO: make this better # noqa: T000
```
When running `flake8` with `flake8-noqa` and `flake8-todo` both installed the user is stuck having either the `T000` warning about the TODO or the `NQA102`. I'm guessing this is related to the behaviour previously partially discussed in https://github.com/plinss/flake8-noqa/issues/26, though slightly different.

I've tried putting the noqa comment both before and after the TODO comment, neither of those works.

**Comment by plinss** [comment]
This is an issue in `flake8-todo`, specifically [these lines](https://github.com/schlamar/flake8-todo/blob/8b48934e6057fc3831eac2091f1f1201beba1abe/flake8_todo.py#L11-L12) need to be simply removed. (And the [pycodestyle import](https://github.com/schlamar/flake8-todo/blob/8b48934e6057fc3831eac2091f1f1201beba1abe/flake8_todo.py#L6) and dependency in `setup.py` can be removed too.)

`flake8-todo` is checking for the existence of a `#noqa` comment and not reporting the violation if present. This is an anti-pattern. `flake8-todo` should simply report the violation and let `flake8` filter out the `#noqa`.

Please file an issue on `flake8-todo`.

**Comment by PeterJCLaw** [comment]
Aha, thanks!
