### ISSUE TITLE
Support flake8==7.0.0

### ISSUE THREAD

**Issue by jonyscathe** [plinss/flake8-noqa#31]
flake8 7 is out so pyproject.toml should probably change from
`	'flake8>=3.8.0,<7.0',`
to
`	'flake8>=3.8.0,<8.0',`

as the breaking changes in flake8==7.0.0 are pretty minor.

I would consider removing the upper bound as well. Flake8 breaking changes are often pretty minor and often don't break anything to do with extensions. And each time there is a new flake8 version, it takes weeks for all the extensions to update their upper bounds for flake8.

https://iscinumpy.dev/post/bound-version-constraints/

**Comment by plinss** [comment]
Fixed in fe5befa, will be on PyPI as v1.4.0.

FWIW, I'm not willing to un-pin the upper bound of flake8 since this plugin does some monkey-patching in flake8's internals.

**Comment by jonyscathe** [comment]
Thanks for the quick fix. And understand not wanting to un-pin the upper bound if you are monkey patching

**Comment by jonyscathe** [comment]
Hey @plinss,
There is no 1.4.0 up on PyPI.
Just checking nothing went wrong with the release?

**Comment by plinss** [comment]
Forgot to push a tag to the production repo, thanks for the catch. Published now.
